### ISSUE TITLE
Don't mute sounds commonly used by AddOns

### ISSUE THREAD

**Issue by Nnoggie** [Nnoggie/PingSounds#1]
The current implementation mutes all sound files.
Some of these sounds are often used by AddOns and should not be muted.
Custom sounds are not affected.
Notable example: DBM uses various sounds for audio cues: "Run away little girl" etc.

**Comment by Nnoggie** [comment]
To expand upon this, possibly add a GUI to allow certain sounds to play

**Comment by Nnoggie** [comment]
fixed in 768cbba7737bb9cf8ef3c14f7a8f6ec135cd6fa4

**Comment by Tigress0125** [comment]
Many addon/game sounds muted and not able to toggle. Examples: ready check, pull timer start.
